### PR TITLE
feat: Init bootstrap source

### PR DESCRIPTION
**Pull request by chauduong1192**

### CODE REVIEW

**Comment by vladnicula** [comment]
screen shot 2018-05-09 at 09 43 58

Looks good I think. :)

**Comment by vladnicula** [comment]
@phatpham9 are you going to accept this or shall I do it?

**Comment by chauduong1192** [comment]
Hi @vladnicula, Phat told me that he invited you as admin of this repo, please check your mailbox and accept it. :D

**Comment by phatpham9** [comment]
@chauduong1192 the travis-ci should be updated to have npm deployment & mattermost notification

**Comment by chauduong1192** [comment]
@phatpham9 ok let me update it.

**Comment by chauduong1192** [comment]
Hi @phatpham9, please give the secure of mattermost notification.

**Comment by vladnicula** [comment]
@chauduong1192 seems like the travis ci is failing. Will you look into this when you get the time?

**Review by vladnicula — APPROVED** [review]

**Pull request merged**
